### ISSUE TITLE
keep_history doesn't work with v2

### ISSUE THREAD

**Issue by travisdowns** [helaili/jekyll-action#101]
In the README the `keep_history` option is documented and an example is given as follows:

![image](https://user-images.githubusercontent.com/2403521/125032154-8b617d80-e05b-11eb-81a5-81c945bb1e77.png)

However, `keep_history` isn't available with `v2` which currently points `v2.1.0`. You'll need to use `@2.2.0` or newer.

**Comment by helaili** [comment]
Should be fix now.
