### ISSUE TITLE
Running `jekyll-action` on GH actions seems to result in enterprise URLs

### ISSUE THREAD

**Issue by rickmark** [helaili/jekyll-action#118]
Having a hard time tracking it down exactly

We are using this (rather now a fork for debug) on GH actions at hack-different/apple-knowledge. The site seems to get bad `relative_url` paths and from a quick look it seems like its using the GH enterprise path - trying to track down if from inside actions it seems to be GH enterprise and if so why it believes so.  Our repo explicitly sets 'baseurl' so it shouldnt happen

**Comment by helaili** [comment]
Can you point me at some log or provide me more details about what you are seeing? There's nothing in this action that caters for GitHub Enterprise so 🤷‍♂️

**Comment by rickmark** [comment]
yeah - so I think I tracked it down to some interaction of the GitHub plugin, and `baseurl: '/'` - not sure why the execution environment comes back with a enterprise like env, but in essence `relative_url` was coming back as `/pages/{owner}/{repo}/` as though it was on an enterprise server.

It must have been fixed - I'll look around for the line that set the pages URL in octokit / jekyll-github-metadata later on - but want this issue so that if others see the same behavior (was solved by setting `baseurl:` to nil

**Comment by lwasser** [comment]
Hi! adding to the convo here, i ran into the exact same thing. I appreciate this issue as it helped m e fix it.

go to your config.yml file
make sure baseurl is set like this (assuming you don't have a /blog path, etc)

```yaml
baseurl : ""
```

THANK YOU @rickmark for saving me a bunch of troubleshooting time. it was adding `pages` to all urls making my linkchecker fail for every link including styles, js files etc in the site!
