### ISSUE TITLE
Source branch detection breaks build_only with no intention of providing API keys

### ISSUE THREAD

**Issue by obilodeau** [helaili/jekyll-action#122]
Hi!

We use this action as a Jekyll verifier, to make sure that the site builds successfully before deploying it using our own means and server. This means that we have no need to provide secrets to this action.

## Problem

Recently when you updated the v2 tag we started getting errors like this:
```
Error: Cannot get GitHub Pages source branch via API.
Error: {
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

![image](https://user-images.githubusercontent.com/546325/154189983-15d63e74-0f86-4fba-8969-e61df5719f29.png)

I'm assuming that its because branch detection requires to use the GitHub API.

## Workaround

Turns out that we need to use the 2.1.0 tag if we want things to work: `helaili/jekyll-action@2.1.0`

## Suggested fix

Since I assume branch detection requires the API token, it would be nice if we could specify the branch to avoid providing our API key to this action.

Thanks for the action btw! It's very useful!

**Comment by helaili** [comment]
Can you give it a try with the head commit (`742d0ede705b0c819d4a13d0f43d3cce07cfe832 `) of #123 ? It should still generate a message about credentials, although it will now be a simple warning with no consequence.

**Comment by obilodeau** [comment]
Yes, it works: 
![image](https://user-images.githubusercontent.com/546325/154285423-0320bef1-4fef-4aa2-bad7-94233873ff72.png)

It doesn't generate a message about credentials but I don't run it in debug either.

**Comment by helaili** [comment]
`v2` tag has been moved to the latest release which includes this fix.
