### ISSUE TITLE
Tag and category pages not accessible on github pages 

### ISSUE THREAD

**Issue by dgmstuart** [helaili/jekyll-action#125]
This is an odd one. I switched from manual deploys to using github actions, and now the tag and category pages get 404 on github pages:

https://dgmstuart.github.io/category/rails
https://dgmstuart.github.io/category/rails/
https://dgmstuart.github.io/category/rails/index.html

The pages seem to exist in the built site on the gh-pages branch:
https://github.com/dgmstuart/dgmstuart.github.io/blob/gh-pages/category/rails/index.html

...and they're linked to from the sitemap:
https://github.com/dgmstuart/dgmstuart.github.io/blob/gh-pages/sitemap.xml

If I build the site locally with `jekyll serve` then the category and tag pages work fine. 

On github pages the https://dgmstuart.github.io/category/ and https://dgmstuart.github.io/tag/ pages work, but the individual links on those pages don't.

I'm not sure if the issue is with this github action, with https://github.com/jekyll/jekyll-archives, with my source code (https://github.com/dgmstuart/dgmstuart.github.io) or with github pages. 

Here's my github workflow: https://github.com/dgmstuart/dgmstuart.github.io/blob/main/.github/workflows/github-pages.yml

Any pointers would be gratefully received!

**Comment by dgmstuart** [comment]
Hello @helaili. Was this closed because you don’t think it’s a bug in jekyll-action?

**Comment by helaili** [comment]
It is most likely a difference between your local environment and the GitHub Pages one, maybe you are missing a dependency when building?
