### ISSUE TITLE
Speed up build time

### ISSUE THREAD

**Issue by KonradHoeffner** [helaili/jekyll-action#130]
On [our project](https://github.com/hitontology/hitontology.eu/runs/6193802938?check_suite_focus=true), jekyll-action takes over 5 minutes to build a small site. Is there a way to speed it up?

**Comment by helaili** [comment]
Did you try using the cache action as shown on [the readme](https://github.com/helaili/jekyll-action#use-the-action)?

**Comment by KonradHoeffner** [comment]
That works perfectly, thanks!
