### ISSUE TITLE
Page does not publish

### ISSUE THREAD

**Issue by Spenhouet** [helaili/jekyll-action#134]
Hi, sorry for the generic issue title but I don't really get what's going on.

Following the instructions [here](https://jekyllrb.com/docs/continuous-integration/github-actions/) and [here](https://github.com/helaili/jekyll-action/blob/master/README.md) I did setup this repository: https://github.com/Spenhouet/jekyll-4-gh-pages-quickstart
And it seems the action is running through without any errors: https://github.com/Spenhouet/jekyll-4-gh-pages-quickstart/runs/6644258159?check_suite_focus=true
Also the expected output is committed to the `gh-pages` branch: https://github.com/Spenhouet/jekyll-4-gh-pages-quickstart/tree/gh-pages

But nonetheless, GitHub does not seem to publish the page: https://spenhouet.com/jekyll-4-gh-pages-quickstart/
Also there is no environment tab as explain in the instructions.

In the project settings for GitHub pages it still looks like that:
![image](https://user-images.githubusercontent.com/7819068/170879380-2835b726-2ee6-4e36-b62f-2250a73c74a0.png)
I'm not sure if it is supposed to. But the instructions said to not touch that, so I didn't. This was supposed to be setup by `jekyll-action`, right?

In this repos sample site there is this init step which is not mentioned in any of the instructions. I tried to include that but that did result in another error: https://github.com/Spenhouet/jekyll-4-gh-pages-quickstart/runs/6644354808?check_suite_focus=true

What is going wrong? 

I hope someone has an idea.

**Comment by helaili** [comment]
Fixed with https://github.com/helaili/jekyll-action/commit/00df63cfdf3d50ae4856a483dc6f1eef95157b9b
