### ISSUE TITLE
Impossible to use the pygment plugin since Python 2 can't be installed

### ISSUE THREAD

**Issue by zedtux** [helaili/jekyll-action#135]
This GH Action has a `Dockerfile` which uses the `ruby:2.7-alpine` image as base image. `ruby:2.7-alpine` ships the Linux Alpine 3.16 which has removed the `python2` packages and only provides Python 3.

Unfortunately, the pygment plugin only work with Python 2.

One easy fix is to change the `Dockerfile` in order to based the Docker image on the `2.7-alpine3.15` image instead allowing to install Python 2 or 3.

A more complex, but flexible way would be to allow the user to configure the `Dockerfile` `FROM` instruction.

**Comment by slonopotamus** [comment]
> the pygment plugin only work with Python 2.

I believe this is no longer true since [pygments.rb 2.0.0](https://github.com/pygments/pygments.rb/releases/tag/v2.0.0)

**Comment by zedtux** [comment]
So what ? Is it fixed one way or another?

**Comment by helaili** [comment]
As per my last change on the README, there's now a much better way to deploy Pages sites, giving you all the flexibility you need to use whatever version of Python.

**Comment by zedtux** [comment]
Thank you for your comment !
