### ISSUE TITLE
Allow commit to be done via github bot

### ISSUE THREAD

**Issue by tielur** [helaili/jekyll-action#141]
Would it be possible to allow a setting to make the commit to the deploy branch be the github bot?

Specifically here:
https://github.com/helaili/jekyll-action/blob/master/entrypoint.sh#L183-L184

I'd like to ideally set `GITHUB_ACTOR` to `github-actions[bot]`

There's a few other actions I've seen do this:
https://github.com/pypa/pipenv/issues/4328
https://github.com/pypa/pipenv/pull/4329

My main reasoning for wanting this is so that my github commit history doesn't get flooded by action commits

**Comment by tielur** [comment]
I'm more then happy to open a PR if this is something that makes sense

**Comment by itrich** [comment]
> I'm more then happy to open a PR if this is something that makes sense

Yes, that would be really awesome and from my point of view a great addition to this action. +1 for this feature!

Another action where this is implemented: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-git-username-and-email

**Comment by UlyssesZh** [comment]
+1 for this feature request. Hope it will be implemented!

**Comment by tielur** [comment]
I have a fork that I made that I've been testing and it works well. I'll work on cleaning it up and open a PR soon
