### ISSUE TITLE
Failed Git Push exits silently

### ISSUE THREAD

**Issue by Xevion** [helaili/jekyll-action#143]
[This][silent-fail-job] job instance that failed to push for me.
- The job exited with an overall success.
- The remote dropped the connection when it was pushed.
- The failure exit code was not picked up by `helaili/jekyll-action@v2`.

I'm not 100% sure about WHY it failed, but [this][unexpected-remote-drop] article specifies it is common with excessively large commits.

I believe my site (at the time) weighed somewhere above 100MB.  After removing assets and re-building, the `gh-pages` branch commit in the action was successful ([example][successful-job]).

[silent-fail-job]: https://github.com/Xevion/v2.xevion.dev/actions/runs/3093857204/jobs/5006672224
[successful-job]: https://github.com/Xevion/v2.xevion.dev/actions/runs/3094030235/jobs/5007008979
[unexpected-remote-drop]: https://everythingtech.dev/2021/03/error-rpc-failed-curl-55-openssl-ssl_write-ssl_error_zero_return-errno-10053/

**Comment by Stwissel** [comment]
Same problem here. The push failed with a 408 which wasn't picked up.
Our site is comparable tiny (< 10 pages0

**Comment by EverettBerry** [comment]
Same problem here. Repo is about 100 MB. Going to try to move some items out.

**Comment by ryan-p-randall** [comment]
I'm also getting the same HTTP 408 error.

When I dig into the commit history, I see this annotation:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Here's a link to that post about [actions running on node16](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).

Maybe it's not the size of the repo, but the action itself needs to be updated to node 16?

**Comment by EverettBerry** [comment]
I tried this upgrade and it did not help.

**Comment by Darkade** [comment]
Same. Upgrade doesn't help. My whole repo is much larger, tho. 295MB

**Comment by EverettBerry** [comment]
Do the steps on the accepted answer. Worked for me.

**Comment by ryan-p-randall** [comment]
Is this the one you mean by the [accepted answer](https://github.com/helaili/jekyll-action/commit/00df63cfdf3d50ae4856a483dc6f1eef95157b9b), @EverettBerry ? Glad something worked for you!

**Comment by inverse** [comment]
Work around worked for me too - very odd though :/

**Comment by helaili** [comment]
As per the updated README there won't be any new changes to this action. 
Thanks!
