### ISSUE TITLE
Incorrect action name in readme example 

### ISSUE THREAD

**Issue by Doreapp** [helaili/jekyll-action#159]
It looks like the [Use case: multi version publishing](https://github.com/helaili/jekyll-action#use-case-multi-version-publishing) in  `README.md` uses the wrong action: `helaili/jekyll-build@v2` instead of `helaili/jekyll-action@v2`  

**Edit**: 

I am using this feature to translate a website ([here for cursious](https://github.com/Doreapp/Doreapp.github.io)), and I ran into an issue with concurrent `git push` in the same branch... I fixed it using [`needs: job1`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds), forcing the translation job to wait for the first one to finish. This may be added in the `README.md`.

In addition, using such a workflow implies to push multiple times to the *Github pages* branch in a row, which triggers *pages build and deployment* workflow several times... Do you have any idea how I could optimize that ?

**Comment by helaili** [comment]
As per the updated README there won't be any new changes to this action. 
Thanks!
