### ISSUE TITLE
When the execution fails, the exit code is 0

### ISSUE THREAD

**Issue by mberlanda** [helaili/jekyll-action#24]
I gave a try to this github action and the first execution was _green_.
I was amazed since I did not configure anything.

Looking at the logs, I could find the following last line:

```
fatal: could not read Username for 'https://github.com': No such device or address
```

Would it be possible to have a non 0 exit code when the job execution fails?

**Comment by helaili** [comment]
Ooops, thanks for catching that. I wrote #27 which should fix this. Do you want to have a look before I merge it?
