### ISSUE TITLE
Ruby version specification

### ISSUE THREAD

**Issue by mberlanda** [helaili/jekyll-action#25]
I run for the first time today this action and I noticed that by default it is using ruby 2.7.0 (with its bunch of deprecation warnings on the most of gems).

Would you be interested in implementing a version specification?

This could be achieved ideally using the `.ruby-version` file generated for rbenv/rvm otherwise via an env var.

In this way you will ensure more consistency in the future runs preventing unexpected breaking changes. Would you need some help to implement it?

**Comment by mberlanda** [comment]
A similar logic could be implemented for `bundler` version. It could be read from the last line of Gemfile.lock or fallback on the default if the file is missing.

**Comment by helaili** [comment]
Thanks for the offer @mberlanda, I'll take it as I'm far from being a :gem: expert
