### ISSUE TITLE
Custom domain is cleared

### ISSUE THREAD

**Issue by pekspro** [helaili/jekyll-action#33]
First, thank you very much for this action. :-)

I have a custom domain on my repository GitHub Pages settings. I have noticed that every time this action is executed this setting is cleared :-( Is there some special setting I need to set to make this work?

**Comment by limjh16** [comment]
Hey! When you add a custom domain from GitHub Pages settings directly, it commits a CNAME file to master branch. However, every time this action runs, if your repository is *.github.io it overwrites the master branch. Thus you'll need to manually create a CNAME file in your source branch. For your case, I think this branch is named "blog".

**Comment by pekspro** [comment]
Thank you so much, @limjh16. I had no idea about that :-)

Instead of checking in a CNAME in my repository, I updated my build workflow instead. After `- uses: actions/checkout@v2` I added this:

	- uses: finnp/create-file-action@master
	  env:
	    FILE_NAME: "./blogfiles/CNAME"
	    FILE_DATA: "my.custom.domain.com"
	
It works beautifully.

**Comment by limjh16** [comment]
Hey! I don't think there's a point to run an action specifically for this purpose, it increases build times and adds complexity, simply committing a file to your source directory should suffice.
