### ISSUE TITLE
Build fails when Coffeescript plugin is used due to missing Javascript runtime

### ISSUE THREAD

**Issue by hexerei** [helaili/jekyll-action#48]
The Coffeescript plugin from Jekyll requires a Javascript runtime installed on the environment.
I get following error when using the Coffeescript plugin:

`Conversion error: Jekyll::Converters::CoffeeScript encountered an error while converting 'media/js/factsheet.coffee':
                    Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.`

On Jekyll Issues page this is documented and fixes describe using either NodeJS or therubyracer Gem.
As I could not deploy NodeJS on your container, I added therubyracer in my Gemfile, which produces following error:

`Dependency Error: Yikes! It looks like you don't have /github/workspace/_plugins/bundler.rb or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the /github/workspace/_plugins/bundler.rb gem in your Gemfile as well. The full error message from Ruby is: 'Error relocating /github/workspace/vendor/bundle/ruby/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.so: __fprintf_chk: symbol not found - /github/workspace/vendor/bundle/ruby/2.7.0/gems/therubyracer-0.12.3/lib/v8/init.so' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
`

Any Idea how this can be fixed?

**Comment by helaili** [comment]
It's similar to https://github.com/helaili/jekyll-action/issues/47#issuecomment-657524361
