### ISSUE TITLE
Add support for CNAME File

### ISSUE THREAD

**Issue by IJustDev** [helaili/jekyll-action#57]
Github needs a CNAME file for custom domains. Auto generate a CNAME file depending on the user input.

The file should look like this:

```
example.com
```

**Comment by baylessj** [comment]
This is how the action should be done, thank you for making this change. Using your fork on my site now.

**Comment by helaili** [comment]
Thanks for this but we've addressed this already in https://github.com/helaili/jekyll-action/pull/39#issuecomment-641536579. TLDR: you just need to commit a file once in you repo, so I don't see the need to write code (and more importantly maintain it) for this.
