### ISSUE TITLE
Using GitHub token

### ISSUE THREAD

**Issue by UweTrottmann** [helaili/jekyll-action#59]
Regarding the ["Known limitation" in the README](https://github.com/helaili/jekyll-action#known-limitation) I wanted to share that for me the following did not work (for a private repo):
```
- uses: helaili/jekyll-action@2.0.4
  env:
    # This does NOT work!
    JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}

fatal: could not read Password for 'https://***@github.com': No such device or address
```

However, this does:
```
- uses: helaili/jekyll-action@2.0.4
  env:
    JEKYLL_PAT: ${{ github.actor }}:${{ github.token }}
```

Note that [`github.token` is the same as `secrets.GITHUB_TOKEN`](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context), I just chose it for consistency (e.g. both work).

Background: I didn't want to use a Personal Access Token because it allows write access to all repos. The token from the `github` context expires once the job is done. Note that I don't use GitHub Pages, so I'm not sure if the above solves the initial deployment issue (see #34). Maybe someone could check?

Thanks for this useful action!

**Comment by AfzalivE** [comment]
I think this is a better way than creating a personal access token that allows access to all repos.

Thank you for sharing!

**Comment by csharpee** [comment]
I was using the personal access token and ran into all kinds of problems pushing to [master](https://github.com/SharpeTronics/sharpetronics.github.io/actions/runs/484351231) on the organizational account. After using the `JEKYLL_PAT: ${{ github.actor }}:${{ github.token }}` the build was possible with v2 and pushed to master and created gh-pages branch as intended.

A while back, i got this working with v2.0.1 only; any other version on the organizational level failed with same result I had above with a new org. account.

Thanks for sharing @UweTrottmann
