### ISSUE TITLE
2.0.4 Could not locate Gemfile

### ISSUE THREAD

**Issue by fiammanda** [helaili/jekyll-action#60]
```
Run helaili/jekyll-action@2.0.4
...
Starting the Jekyll Action
Could not locate Gemfile
```

It works well with 2.0.0
```
Starting the Jekyll Action
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
```

**Comment by helaili** [comment]
Do you have a `Gemfile.lock` file in your repo?

**Comment by fiammanda** [comment]
> 
> 
> Do you have a `Gemfile.lock` file in your repo?

No, I don't, since the [tutorial](https://jekyllrb.com/docs/continuous-integration/github-actions/) does not include one. If requied, what should be in the `Gemfile.lock`?

**Comment by helaili** [comment]
See https://github.com/helaili/jekyll-action/issues/54#issuecomment-685463610

**Comment by fiammanda** [comment]
> 
> 
> See [#54 (comment)](https://github.com/helaili/jekyll-action/issues/54#issuecomment-685463610)

I include `Gemfile.lock` now but it still shows `Could not locate Gemfile`

**Comment by helaili** [comment]
Is [this](https://github.com/fiammanda/test) your repo? I can't find the `Gemfile.lock` in it.

**Comment by fiammanda** [comment]
> 
> 
> Is [this](https://github.com/fiammanda/test) your repo? I can't find the `Gemfile.lock` in it.

I met this error and switch back to 2.0.0...
```
Your bundle only supports platforms ["x64-mingw32"] but your local platforms are
["ruby", "x86_64-linux-musl"], and there's no compatible match between those two
lists.
```

**Comment by helaili** [comment]
This is most likely a problem with your Ruby setup. Maybe you should try running the workflow on windows runner, replacing [this line](https://github.com/fiammanda/test/blob/54d672ba7107afee118a9144e8b933fac4e45d1d/.github/workflows/jekyll.yml#L10) by: 

```yaml
    runs-on: windows-latest
```

**Comment by fiammanda** [comment]
> 
> 
> This is most likely a problem with your Ruby setup. Maybe you should try running the workflow on windows runner, replacing [this line](https://github.com/fiammanda/test/blob/54d672ba7107afee118a9144e8b933fac4e45d1d/.github/workflows/jekyll.yml#L10) by:
> 
> ```yaml
>     runs-on: windows-latest
> ```

` Error: Container action is only supported on Linux`

**Comment by sebranchett** [comment]
Having exactly the same issue. Working on Windows, action only works for ubuntu.
Removing Gemfile.lock leads to message that Gemfile cannot be located.
Adding Gemfile.lock (generated on Windows) causes all sorts of problems.
Managed to get action working by manually editing my Gemfile.lock, removing all references to -x64-mingw32, and adding the ruby platform:
--    eventmachine (1.2.7-x64-mingw32)
--    ffi (1.13.1-x64-mingw32)
++    eventmachine (1.2.7)
++    ffi (1.13.1)
--    sassc (2.4.0-x64-mingw32)
++    sassc (2.4.0)
 PLATFORMS
   x64-mingw32
++  ruby

Would be nice if this action could generate a (linux) Gemfile.lock for you.

Very pleased that this action exists and that I got it working!

**Comment by fiammanda** [comment]
> Having exactly the same issue. Working on Windows, action only works for ubuntu.
> Removing Gemfile.lock leads to message that Gemfile cannot be located.
> Adding Gemfile.lock (generated on Windows) causes all sorts of problems.
> Managed to get action working by manually editing my Gemfile.lock, removing all references to -x64-mingw32, and adding the ruby platform:
> -- eventmachine (1.2.7-x64-mingw32)
> -- ffi (1.13.1-x64-mingw32)
> ++ eventmachine (1.2.7)
> ++ ffi (1.13.1)
> -- sassc (2.4.0-x64-mingw32)
> ++ sassc (2.4.0)
> PLATFORMS
> x64-mingw32
> ++ ruby
> 
> Would be nice if this action could generate a (linux) Gemfile.lock for you.
> 
> Very pleased that this action exists and that I got it working!

Thank so much for sharing! I will try if it works with local building, and if not I will go with the previous version for now.

**Comment by igsoblechero** [comment]
Hi! Same issue as above. I basically followed the [official GitHub Actions tutorial](https://jekyllrb.com/docs/continuous-integration/github-actions/) but tried to use version 2.0.4 instead of 2.0.1. It works up to 2.0.3, so it looks like it's an error on the `Gemfile` search logic.

I can totally generate a `Gemfile.lock` file as I'm working on Linux. However, I'm surprised I'm forced to do it for version 2.0.4, specially since the tutorial explicitly tells us not to push that file. Any reason for this?

**Comment by qwtel** [comment]
> Could someone try using `helaili/jekyll-action@30a62b6` to see if it does the trick?

This did not do the trick for me:

```
The deployment setting requires a Gemfile.lock. Please make sure you have
checked your Gemfile.lock into version control before deploying.
```

**Comment by helaili** [comment]
Can you provide a link to the repo with this problem?

**Comment by fiammanda** [comment]
Not working, please kindly refer to https://github.com/fiammanda/fiammanda.github.io/runs/1338863719?check_suite_focus=true

**Comment by qwtel** [comment]
Sorry, couldn't make it public at this point. As I understand it, setting `

> Can you provide a link to the repo with this problem?

https://github.com/getclaps/site/runs/1335328771?check_suite_focus=true

**Comment by jasonpatrickellykrause** [comment]
> Could someone try using `helaili/jekyll-action@30a62b6` to see if it does the trick?

Negative. 

[https://github.com/jasonpatrickellykrause/JasonPatricKellyKrause.github.io/runs/1368033531?check_suite_focus=true](url)

**Comment by helaili** [comment]
I think I now got it right. At least it's now working in a fork of [@fiammanda's repo](https://github.com/helaili/fiammanda.github.io/runs/1402277366?check_suite_focus=true)

Another try using `helaili/jekyll-action@56f7087` to confirm, anyone?

**Comment by BenResTech** [comment]
Can confirm it is working on that commit @helaili 
https://github.com/BenResTech/BenResTech.github.io/runs/1431367831?check_suite_focus=true
