### ISSUE TITLE
Add option for build-only / "dry run"

### ISSUE THREAD

**Issue by qwtel** [helaili/jekyll-action#63]
I'm using this action to prepare a site to be deployed via https://github.com/cloudflare/wrangler-action.

For this use case, pushing to `gh-pages` is unnecessary. While not strictly speaking necessary, it would be nice to have an option for skipping this part.

**Comment by qwtel** [comment]
Yes. Basically it should end after `echo "Jekyll build done"`

**Comment by andrewbanchich** [comment]
Also looking for this so I can have a workflow to just test that it builds properly for PRs and one to deploy when merged.
