### ISSUE TITLE
Webp fails to cratefile

### ISSUE THREAD

**Issue by marksie1988** [helaili/jekyll-action#81]
Iam using jekyll-webp to convert images to webp, when I run a build locally it works without issue but using this action it fails to convert 

```
WebP: Conversion for image /github/workspace/assets/images/articles/2020-05-05-docker-overlay2-centos-production.png failed, no webp version could be created for this image
```

Any ideas what's causing this or how to resolve?

**Comment by helaili** [comment]
No idea 🤷
