### ISSUE TITLE
Apt packages gone crazy

### ISSUE THREAD

**Issue by 0atman** [helaili/jekyll-action#9]
Checking my logs after a 3-minute apt install step, I note the apt install pulls in gtk libraries and emacs! I doubt that was intentional!

https://github.com/helaili/jekyll-action/blob/master/Dockerfile#L16

**Comment by 0atman** [comment]
:laughing:

**Comment by elindsey** [comment]
Related to https://github.com/helaili/jekyll-action/pull/10

**Comment by Axel-Naumann** [comment]
https://launchpad.net/ubuntu/+source/gem - gem is not what you think it is.

**Comment by 0atman** [comment]
@Axel-Naumann is right, the ubuntu package is called `rubygems-integration`, does git-all accidentally pull in `gem`?

**Comment by helaili** [comment]
I've cleaned up the dependencies, it should be faster now.

**Comment by 0atman** [comment]
looks great, thanks @helaili! :ok_hand:
