### ISSUE TITLE
Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml

### ISSUE THREAD

**Issue by locness3** [helaili/jekyll-action#91]
Hi, I'm following the guide from [here](https://jekyllrb.com/docs/continuous-integration/github-actions/) to try and deploy the website from [***this repo***](https://github.com/csourcesc/csourcesc.github.io), because I want to use jekyll-archives.

I set up the workflow in `.github/workflows/github-pages.yml`. It fails when building the site, with this error :
```
Liquid Exception: Liquid syntax error (line 8): Unknown tag 'when' in vendor/bundle/ruby/2.7.0/gems/liquid-4.0.3/lib/liquid/locales/en.yml
```
My full log is here : [log.txt](https://github.com/helaili/jekyll-action/files/6266366/log.txt)

Why is this? Can I fix it? Thanks in advance for any answer.

**Comment by helaili** [comment]
I did a quick google and it seems that others have had a similar error in a totally different context. I don't think this is linked to this action.

**Comment by locness3** [comment]
The solution I found for this is to remove the .bundle and vendor directories.... which aren't present in my repository.
