### ISSUE TITLE
Gem Caching doesn't work as advertised

### ISSUE THREAD

**Issue by buddhist-uni** [helaili/jekyll-action#95]
Amazing Action! It does exactly what it says on the box 😄 Thanks!

Just wanted to point out that the gem caching in your readme doesn't work, since the bundle install is inside the docker image, not the runner itself, and so the cacher cannot see those files. There may be some way to ask bundler to put vendor/ in one of the shared working directories but that's a bit beyond my skill at the moment. Hopefully someone can get the gem caching working.

Anyway, thanks again for the stellar script! 😄

**Comment by buddhist-uni** [comment]
Got it to work! Here's what I had to do:

- Use @2.2 instead of @v2 tag
- Instead of caching `path: vendor/bundle` cache `path: ${{ github.workspace }}/vendor`

Now it works like a charm! I suggest updating the README accordingly. Cheers!

**Comment by nathankitchen** [comment]
@buddhist-uni I've run into the same problem and am attempting your solution. Could you clarify whether using helaili/jekyll-action@2.2 or actions/cache@2.2 fixed your issue? Also did you mean to drop the `v` there?

It would save me some time if you're able to clarify, I'm currently "brute forcing" the various options.

**Comment by buddhist-uni** [comment]
> helaili/jekyll-action@2.2

This one. I'm using `cache@v2`



> did you mean to drop the `v` there?

Yes. Check out [the tags list](https://github.com/helaili/jekyll-action/tags) for your ref options

> if you're able to clarify, I'm currently "brute forcing" the various options.

[Here is my production build workflow](https://github.com/buddhist-uni/buddhist-uni.github.io/blob/master/.github/workflows/build.yaml) which is currently working for me in case that's helpful 😄
