### ISSUE TITLE
"publish only" mode

### ISSUE THREAD

**Issue by travisdowns** [helaili/jekyll-action#99]
Thanks for this great tool.

In the same way there is a `build_only` mode, it would be nice to have a publish-only mode. For example, I already have an action to build the site using Jekyll, and I run some tests, etc, on this output, then I'd like to use this plugin to publish the site that I tested, not the one built using this tool (which uses a slightly different approach).

Perhaps this is already some way to accomplish this that I'm missing, I'm not sure.

**Comment by helaili** [comment]
You can have a look at what I do in `.github/actions/publish/action.yml`.
